apiVersion: v1
kind: Service
metadata:
  name: performance-testing-api-dev
  labels:
    role: hedra
    name: api
spec:
  ports:
  - port: 6669
    name: leader-comm
  - port: 6670
    name: worker-comm
  - port: 6671
    name: updates-comm
  - port: 9001
    name: statserve-out
  - port: 9002
    name: api-out
    protocol: TCP
  selector:
    role: hedra
    name: api
  type: NodePort