from enum import Enum


class HookType(Enum):
    ACTION='ACTION'
    AFTER='AFTER'
    BEFORE='BEFORE'
    CHANNEL='CHANNEL'
    CHECK='CHECK'
    CONTEXT='CONTEXT'
    CONDITION='CONDITION'
    EVENT='EVENT'
    INTERNAL='INTERNAL'
    METRIC='METRIC'
    LOAD='LOAD'
    SAVE='SAVE'
    SETUP='SETUP'
    TASK='TASK'
    TEARDOWN='TEARDOWN'
    TRANSFORM='TRANSFORM'
    VALIDATE='VALIDATE'
