from enum import Enum


class HookType(Enum):
    ACTION='ACTION'
    SETUP='SETUP'
    TEARDOWN='TEARDOWN'
    BEFORE='BEFORE'
    AFTER='AFTER'
    BEFORE_BATCH='BEFORE_BATCH'
    AFTER_BATCH='AFTER_BATCH'
