from enum import Enum


class StageStates(Enum):
    INITIALIZED='INITIALIZED'
    SETTING_UP='SETTING_UP'
    SETUP='SETUP'
    OPTIMIZING='OPTIMIZING'
    OPTIMIZED='OPTIMIZED'
    EXECUTING='EXECUTING'
    EXECUTED='EXECUTED'
    ANALYZING='ANALYZING'
    ANALYZED='ANALYZED'
    CHECKPOINTING='CHECKPOINTING'
    CHECKPOINTED='CHECKPOINTED'
    COMPLETE='COMPLETE'
    ERRORED='ERRORED'